apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoproject
  labels:
    app: demoproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoproject
  template:
    metadata:
      labels:
        app: demoproject
    spec:
      containers:
      - name: demoproject-container
        image: garimakewat/demoproject
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: demoproject-np-service
  labels:
    app: demoproject
spec:
  selector:
    app: demoproject

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
